---
- name: Create ochap-backend configuration directories
  file:
    path: /opt/wildfly/modules/ch/heigvd/amt/ochap_backend/configuration/main
    state: directory

- name: Install ochap-backend configuration module
  template:
    src: ochap_backend.module.xml
    dest: /opt/wildfly/modules/ch/heigvd/amt/ochap_backend/configuration/main/module.xml

- name: Install ochap-backend application.properties
  template:
    src: ochap_backend.application.properties
    dest: /opt/wildfly/modules/ch/heigvd/amt/ochap_backend/configuration/main/application.properties

- name: Remove possibly stranded ochap-usermgmt configuration directories
  file:
    path: /opt/wildfly/modules/ch/heigvd/amt/ochap_usermgmt/configuration/main
    state: absent

- name: Remove possibly stranded ochap-usermgmt configuration directories
  file:
    path: /opt/wildfly/modules/ch/heigvd/amt/ochap_usermgmt/configuration/main
    state: absent

- name: Create ochap data directory
  file:
    path: "{{ ochap_backend_datadir }}"
    state: directory
    owner: wildfly
    mode: 0700

- name: Find old WARs
  find:
    paths: /opt/wildfly/standalone/deployments
    patterns: "*.war"
    use_regex: true
  register: wildcard_old_wars

- name: Remove old WARs
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ wildcard_old_wars.files }}"

- name: "Copy Ô Chap' WARs"
  copy:
    src: "{{ item }}"
    dest: /opt/wildfly/standalone/deployments
    owner: wildfly
    mode: 0444
  with_items: "{{ wars_to_deploy }}"

- name: Enable WildFly service and set to start at boot
  service:
    name: wildfly
    state: restarted
